import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from "@react-oauth/google";
import { AppProvider } from "@/context/AppContext";
import Navbar from "./components/navbar/Navbar";
import AlertStack from "./components/AlertStack";
import { I18nProvider } from "@/i18n/I18nProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}
      >
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
              <I18nProvider>
                  <AppProvider>
                      <AlertStack />
                      <Navbar />
                      {children}
                  </AppProvider>
              </I18nProvider>
          </GoogleOAuthProvider>
      </body>
    </html>
  );
}
